### ISSUE TITLE
Update account responses

### ISSUE THREAD

**Issue by destenson** [rideron89/tda-sdk-rs#5]
I just started trying to use this crate & found that `Client::get_accounts()` returns an unparsable response for me. There are a number of fields that are extra or missing in the `InitialBalances`, `CurrentBalances`, and `ProjectedBalances` structs.

I will make a PR to add these fields and change missing fields to `Option<_>`.

**Comment by rideron89** [comment]
Thanks for the ticket. I just pulled your pull request down and the tests are still passing so I'll merge it in soon.

I was actually thinking of refactoring and removing the hardcoded response structs so consumers can define the responses to fit their program. Anyway, I appreciate the help!

**Comment by rideron89** [comment]
Published as v0.1.4
